StartupEvents.registry('item', event => {
    event.create("amber_earrings",'helmet').displayName("Amber Earrings").rarity("common").tooltip("One of the items sold by the Gerudo jeweler. These earrings are made with amber, a gem that harnesses the power of the land to increase defense when equipped.")
    event.create("amber_earrings_t1",'helmet').displayName("Amber Earrings ★").rarity("uncommon").tooltip("Earrings made with amber, a gem that harnesses the power of the land to increase your defense. A Great Fairy has increased their defense by one level.")
    event.create("amber_earrings_t2",'helmet').displayName("Amber Earrings ★★").rarity("uncommon").tooltip("Earrings made with amber, a gem that harnesses the power of the land to increase your defense. A Great Fairy has increased their defense by two levels.")
    event.create("amber_earrings_t3",'helmet').displayName("Amber Earrings ★★★").rarity("uncommon").tooltip("Earrings made with amber, a gem that harnesses the power of the land to increase your defense. A Great Fairy has increased their defense by three levels")
    event.create("amber_earrings_t4",'helmet').displayName("Amber Earrings ★★★★").rarity("rare").tooltip("Earrings made with amber, a gem that harnesses the power of the land to increase your defense. A Great Fairy has increased their defense to its maximum level.")
    event.create("ancient_helm",'helmet').displayName("Ancient Helm").rarity("common").tooltip("This headgear is the result of Robbie's research. It uses Guardian parts to decrease damage from ancient energy attacks.")
    event.create("ancient_helm_t1",'helmet').displayName("Ancient Helm ★").rarity("uncommon").tooltip("Headgear that uses Guardian parts to decrease the damage from ancient energy attacks. A Great Fairy has increased its defense by one level.")
    event.create("ancient_helm_t2",'helmet').displayName("Ancient Helm ★★").rarity("uncommon").tooltip("Headgear that uses Guardian parts to decrease the damage from ancient energy attacks. A Great Fairy has increased its defense by two levels.")
    event.create("ancient_helm_t3",'helmet').displayName("Ancient Helm ★★★").rarity("uncommon").tooltip("Headgear that uses Guardian parts to decrease the damage from ancient energy attacks. A Great Fairy has increased its defense by three levels.")
    event.create("ancient_helm_t4",'helmet').displayName("Ancient Helm ★★★★").rarity("rare").tooltip("Headgear that uses Guardian parts to decrease the damage from ancient energy attacks. A Great Fairy has increased its defense to its maximum level.")
    event.create("medoh_dev_helm",'helmet').displayName("Vah Medoh Devine Helm").rarity("common").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities.")
    event.create("medoh_dev_helm_t1",'helmet').displayName("Vah Medoh Devine Helm ★").rarity("uncommon").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities. A Great Fairy has increased its defense by one level.")
    event.create("medoh_dev_helm_t2",'helmet').displayName("Vah Medoh Devine Helm ★★").rarity("uncommon").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities. A Great Fairy has increased its defense by two levels.")
    event.create("medoh_dev_helm_t3",'helmet').displayName("Vah Medoh Devine Helm ★★★").rarity("uncommon").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities. A Great Fairy has increased its defense by three levels.")
    event.create("medoh_dev_helm_t4",'helmet').displayName("Vah Medoh Devine Helm ★★★★").rarity("rare").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities. A Great Fairy has increased its defense to its maximum level.")
    event.create("naboris_dev_helm", 'helmet').displayName("Vah Naboris Devine Helm").rarity("common").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities.")
    event.create("naboris_dev_helm_t1", 'helmet').displayName("Vah Naboris Devine Helm ★").rarity("common").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities. A Great Fairy has increased its defense by one level.")
    event.create("naboris_dev_helm_t2", 'helmet').displayName("Vah Naboris Devine Helm ★★").rarity("common").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities. A Great Fairy has increased its defense by two levels.")
    event.create("naboris_dev_helm_t3", 'helmet').displayName("Vah Naboris Devine Helm ★★★").rarity("common").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities. A Great Fairy has increased its defense by three levels.")
    event.create("naboris_dev_helm_t4", 'helmet').displayName("Vah Naboris Devine Helm ★★★★").rarity("common").tooltip("A treasure gifted to the one who controls Divine Beast Vah Naboris. It endows its user with enhanced abilities. A Great Fairy has increased its defense to its maximum level.")
    event.create("rudania_dev_helm", 'helmet').displayName("Vah Rudania Devine Helm").rarity("common").tooltip("A treasure gifted to the one who controls Divine Beast Vah Rudania. It endows its user with enhanced abilities.")
    event.create("rudania_dev_helm_t1", 'helmet').displayName("Vah Rudania Devine Helm ★").rarity("common").tooltip("A treasure gifted to the one who controls Divine Beast Vah Rudania. It endows its user with enhanced abilities. A Great Fairy has increased its defense by one level.")
    event.create("rudania_dev_helm_t2", 'helmet').displayName("Vah Rudania Devine Helm ★★").rarity("uncommon").tooltip("A treasure gifted to the one who controls Divine Beast Vah Rudania. It endows its user with enhanced abilities. A Great Fairy has increased its defense by two levels.")
    event.create("rudania_dev_helm_t3", 'helmet').displayName("Vah Rudania Devine Helm ★★★").rarity("uncommon").tooltip("A treasure gifted to the one who controls Divine Beast Vah Rudania. It endows its user with enhanced abilities. A Great Fairy has increased its defense by three levels.")
    event.create("rudania_dev_helm_t4", 'helmet').displayName("Vah Rudania Devine Helm ★★★★").rarity("rare").tooltip("A treasure gifted to the one who controls Divine Beast Vah Rudania. It endows its user with enhanced abilities. A Great Fairy has increased its defense to its maximum level.")
    event.create("ruta_dev_helm",'helmet').displayName("Vah Ruta Devine Helm").rarity("common").tooltip("A treasure gifted to the one who controls Divine Beast Vah Ruta. It endows its user with enhanced abilities")
    event.create("ruta_dev_helm_t1",'helmet').displayName("Vah Ruta Devine Helm ★").rarity("uncommon").tooltip("A treasure gifted to the one who controls Divine Beast Vah Ruta. It endows its user with enhanced abilities. A Great Fairy has increased its defense by one level.")
    event.create("ruta_dev_helm_t2",'helmet').displayName("Vah Ruta Devine Helm ★★").rarity("uncommon").tooltip("A treasure gifted to the one who controls Divine Beast Vah Ruta. It endows its user with enhanced abilities. A Great Fairy has increased its defense by two levels.")
    event.create("ruta_dev_helm_t3",'helmet').displayName("Vah Ruta Devine Helm ★★★").rarity("uncommon").tooltip("A treasure gifted to the one who controls Divine Beast Vah Ruta. It endows its user with enhanced abilities. A Great Fairy has increased its defense by three levels.")
    event.create("ruta_dev_helm_t4",'helmet').displayName("Vah Ruta Devine Helm ★★★★").rarity("rare").tooltip("A treasure gifted to the one who controls Divine Beast Vah Ruta. It endows its user with enhanced abilities. A Great Fairy has increased its defense to its maximum level.")
    event.create("ancient_cuirass",'chestplate').displayName("Ancient Cuirass").rarity("common").tooltip("This armor was created by ancient Sheikah technology using Guardian parts. Equipping it will reduce the damage you take from ancient weaponry.")
    event.create("ancient_cuirass_t1",'chestplate').displayName("Ancient Cuirass ★").rarity("uncommon").tooltip("Armor made from ancient Sheikah technology and Guardian parts. Reduces damage from ancient weapons. A Great Fairy increased its defense by one level.")
    event.create("ancient_cuirass_t2",'chestplate').displayName("Ancient Cuirass ★★").rarity("uncommon").tooltip("Armor made from ancient Sheikah technology and Guardian parts. Reduces damage from ancient weapons. A Great Fairy increased its defense by two levels.")
    event.create("ancient_cuirass_t3",'chestplate').displayName("Ancient Cuirass ★★★").rarity("uncommon").tooltip("Armor made from ancient Sheikah technology and Guardian parts. Reduces damage from ancient weapons. A Great Fairy increased its defense by three levels.")
    event.create("ancient_cuirass_t4",'chestplate').displayName("Ancient Cuirass ★★★★").rarity("rare").tooltip("Armor made from ancient Sheikah technology and Guardian parts. Reduces damage from ancient weapons. A Great Fairy increased its defense to its maximum level.")
    event.create("ancient_greaves",'leggings').displayName("Ancient Greaves").rarity("common").tooltip("Robbie engineered these greaves at the research institute using the same technology found in Guardian automata. They reduce damage from ancient weaponry.")
    event.create("ancient_greaves_t1",'leggings').displayName("Ancient Greaves ★").rarity("uncommon").tooltip("These greaves use the same technology found in Guardian automata, which reduces damage from ancient weaponry. A Great Fairy increased their defense by one level.")
    event.create("ancient_greaves_t2",'leggings').displayName("Ancient Greaves ★★").rarity("uncommon").tooltip("These greaves use the same technology found in Guardian automata, which reduces damage from ancient weaponry. A Great Fairy increased their defense by two levels.")
    event.create("ancient_greaves_t3",'leggings').displayName("Ancient Greaves ★★★").rarity("uncommon").tooltip("These greaves use the same technology found in Guardian automata, which reduces damage from ancient weaponry. A Great Fairy increased their defense by three levels.")
    event.create("ancient_greaves_t4",'leggings').displayName("Ancient Greaves ★★★★").rarity("rare").tooltip("These greaves use the same technology as Guardians to reduce damage from ancient weaponry. A Great Fairy raised their defense to its maximum level.")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")
    event.create("",'helmet').displayName("").rarity("").tooltip("")






})






//    event.create("",'helmet').displayName("").rarity("").tooltip("")
