ItemEvents.toolTierRegistry(event => {
  event.add('Admin', tier => {
    tier.uses = 9999
    tier.speed = 0.1
    tier.attackDamageBonus = 9999.0
    tier.level = 9999
    tier.enchantmentValue = 0
  })
})

ItemEvents.armorTierRegistry(event => {
  event.add('Admin', tier => {
    tier.durabilityMultiplier = 9999 // Each slot will be multiplied with [13, 15, 16, 11]
    tier.slotProtections = [999, 999, 999, 999] // Slot indicies are [FEET, LEGS, BODY, HEAD] 
    tier.enchantmentValue = 9999
    tier.equipSound = 'minecraft:item.armor.equip_netherite'
    tier.toughness = 9999.0 // diamond has 2.0, netherite 3.0
    tier.knockbackResistance = 9999.0
  })
})


StartupEvents.registry('item', e => {
  //Admin tools
   e.create('admin_hammer', "sword").displayName("Ban Hammer").tier('Admin').unstackable().rarity('rare').tooltip("oooh. Shiny")
   e.create('admin_sword', 'sword').tier('Admin').unstackable().rarity('rare').tooltip("oooh. Shiny")
   e.create('admin_axe', 'axe').tier('Admin').unstackable().rarity('rare').tooltip("oooh. Shiny")
   e.create('admin_pickaxe', 'pickaxe').tier('Admin').unstackable().rarity('rare').tooltip("oooh. Shiny")
   e.create('admin_shovel', 'shovel').tier('Admin').unstackable().rarity('rare').tooltip("oooh. Shiny")
   e.create('admin_hoe', 'hoe').tier('Admin').unstackable().rarity('rare').tooltip("Node, not that kind of hoe")
  //admin armor
   e.create('admin_helmet', 'helmet').tier('Admin').unstackable().rarity('rare').tooltip("oooh. Shiny")
   e.create('admin_chestplate', 'chestplate').tier('Admin').unstackable().rarity('rare').tooltip("oooh. Shiny")
   e.create('admin_leggings', 'leggings').tier('Admin').unstackable().rarity('rare').tooltip("oooh. Shiny")
   e.create('admin_boots', 'boots').tier('Admin').unstackable().rarity('rare').tooltip("oooh. Shiny")
  //comunity weapons
   e.create('master_sword', 'sword').attackDamageBaseline(30.0).glow(true).maxDamage(20).displayName("Master Sword").unstackable().rarity('rare').tooltip("The Legendary sword that seals the darkness. It's blade gleams with a sacred luster that can oppose the Calamity. Only a hero chosen by the sword itself may wield it.")
   e.create('tree_sword', 'sword').displayName("Tree Branch").attackDamageBaseline(2.0).maxDamage(4).unstackable().rarity('common').tooltip("Wooden branches such as this are pretty common, but it's urprisingly well-balanced. It doesn't do much damage but can serve as a weapon in a pinch.")
   e.create('traveller_sword', 'sword').displayName("Traveller's Sword").attackDamageBaseline(5.0).maxDamage(20).unstackable().rarity('common').tooltip("A very common sword often kept by travelers to fend off small beasts. It's fairly durable, but a bit unreliable against monsters.")
   e.create('soldier_bsword','sword').displayName("Soldier's Broadsword").attackDamageBaseline(14.0).maxDamage(25).unstackable().rarity('common').tooltip("A Sword brandished by the soldiers who once protected Hyrule Castle. Its durable blade is well tuned for slaying monsters.")
   e.create('knights_bsword', 'sword').displayName("Knight's Broadsword").attackDamageBaseline(26.0).maxDamage(27).unstackable().rarity('common').tooltip("Knights of Hyrule once carried this sword. These days it's the weapon of choice for seasoned adventurers thanks to its ease of use and high attack power.")
   e.create('royal_bsword', 'sword').displayName("Royal Broadsword").attackDamageBaseline(36.0).maxDamage(36).unstackable().rarity('uncommon').tooltip("	The Hyrulean royal family would award this sword to knights who achieved remarkable feats. A sword that balances strength and beauty as elegantly as this one is a rare find.")
   e.create('forest_dweller_sword', 'sword').displayName("Forest Dweller's Sword").attackDamageBaseline(22).maxDamage(27).unstackable().rarity('uncommon').tooltip("Koroks made this sword for Hylians. It's made of wood, so it isn't the best choice for head-on attacks. Its original intent was likely clearing vines to forge paths through forests.")
   e.create('zora_sword', 'sword').displayName("Zora sword").attackDamageBaseline(15.0).maxDamage(27).unstackable().rarity('common').tooltip("The ornamentation that adorns this blade is a traditional Zora design. It's forged from a very durable and rust-proof metal.")
   e.create('feathered_sword', 'sword').displayName("Feathered Edge").attackDamageBaseline(15.0).maxDamage(27).unstackable().rarity('common').tooltip("Rito craftsmen forged this lightweight, double-edge sword so Rito warriors could soar into battle unhindered by its weight.")
   e.create('gerudo_sword', 'sword').displayName("Gerudo Scimitar").attackDamageBaseline(16.0).maxDamage(23).unstackable().rarity('common').tooltip("This common sword is often carried by Gerudo women for self-defense. Its short, curved blade is easily recognized.")
   e.create('moonlight_sword', 'sword').displayName("Moonlight Scimitar").attackDamageBaseline(25.0).maxDamage(32).unstackable().rarity('common').tooltip("Delicate Gerudo carvings decorate this curved sword. The engraved blade is extremely sharp. Apparently it once served ceremonial purposes in festivals.")
   e.create('seven_sword', 'sword').displayName("Scimitar of the Seven").attackDamageBaseline(32.0).maxDamage(60).unstackable().rarity('common').tooltip("A famous sword once beloved by the Gerudo Champion Urbosa. It is said that when Urbosa swung this sword in battle, her movements resembled a beautiful dance.")
   e.create('eightfold_sword', 'sword').displayName("Eightfold Blade").attackDamageBaseline(15.0).maxDamage(26).unstackable().rarity('common').tooltip("A single-edged sword traditional to the Sheikah tribe. Forged using ancient technology it just may be among the sharpest conventional weapons ever made.")
   e.create('ancient_ssword', 'sword').displayName("Ancient Short Sword").attackDamageBaseline(40.0).maxDamage(54).unstackable().rarity('common').tooltip("The blade of this sword was made using an ancient power lost to this modern age. Its blade appears only when drawn, and its cutting power surpasses metal swords.")
   e.create('rusty_bsword', 'sword').displayName("Rusty Broadsword").attackDamageBaseline(6.0).maxDamage(8).unstackable().rarity('common').tooltip("A rusty sword used ages ago by a skilled swordsman. It can do some damage in the right hands but also breaks quickly.")
   e.create('guard_sword', 'sword').displayName("Royal Guard's Sword").attackDamageBaseline(48.0).maxDamage(14).unstackable().rarity('common').tooltip("A Sheikah-made replica of the sword that seals the darkness. It was made with ancient technology to oppose the Great Calamity, but its low durability made it inefficient.")
   e.create('flame_sword', 'sword').displayName("Flameblade").attackDamageBaseline(24.0).maxDamage(36).unstackable().rarity('common').tooltip("This magical sword was forged in the lava of Death Mountain. It leaves white-hot flames in its wake when the blade glows red.")
   e.create('frost_sword', 'sword').displayName("Frostblade").attackDamageBaseline(20.0).maxDamage(30).unstackable().rarity('common').tooltip("A magical sword forged in the frigid mountains of the Hebra region. When the blade glows blue, enemies struck by it will become frozen.")
   e.create('thunder_sword', 'sword').displayName("Thunderblade").attackDamageBaseline(22.0).maxDamage(36).unstackable().rarity('common').tooltip("A magical sword forged and refined by lightning from the Hyrule Hills. When the blade shines with a golden light, it will electrocute enemies struck by it.")
   e.create('goddess_sword', 'sword').displayName("Goddess Sword").attackDamageBaseline(28.0).maxDamage(45).unstackable().rarity('rare').tooltip("A sword said to have once belonged to a hero from the sky. Its blade houses the fire of the Goddess. When wielded, a strange yet heavenly breeze kicks up around you.")
   e.create('8bit_sword', 'sword').displayName("Sword").attackDamageBaseline(22.0).maxDamage(27).unstackable().rarity('rare').tooltip("A sword once wielded by a hero in an ancient age. When grasped, a strange sense of nostalgia washes over you. Take it when going alone would otherwise be dangerous.")
   e.create('boko_sword', 'sword').displayName("Boko Club").attackDamageBaseline(4.0).maxDamage(8).unstackable().rarity('common').tooltip("A crude Bokoblin club made to clobber small prey. It's essentially a stick, so its durability is low.")
   e.create('spiked_boko_sword', 'sword').displayName("Spiked Boko Club").attackDamageBaseline(12.0).maxDamage(14).unstackable().rarity('common').tooltip("A reinforced Bokoblin club made to maximize damage. The sharpened bones jabbed into it make it a brutal weapon")
   e.create('bone_boko_sword', 'sword').displayName("Dragonbone Boko Club").attackDamageBaseline(24.0).maxDamage(18).unstackable().rarity('common').tooltip("This Bokoblin club has been reinforced with fossilized bones to maximize clobbering potential. Only the brawniest of Bokoblins can manage its immense weight.")
   e.create('guardian_sword', 'sword').displayName("Guardian Sword").attackDamageBaseline(20.0).maxDamage(17).unstackable().rarity('common').tooltip("A sword often wielded by Guardian Scouts. Its blue energy blade is a product of ancient technology. It's not very durable.")
   e.create('plus_guardian_sword', 'sword').displayName("Guardian Sword+").attackDamageBaseline(30.0).maxDamage(26).unstackable().rarity('common').tooltip("This Guardian sword has enhanced power over the standard model. Its cutting capabilities are improved, and its durability has seen a slight uptick.")
   e.create('dplus_guardian_sword', 'sword').displayName("Guardian Sword++").attackDamageBaseline(40.0).maxDamage(32).unstackable().rarity('common').tooltip("The abilities of this Guardian sword have been boosted to the maximum, as evidenced by its increase in size. It slices through armor like a hot knife through butter!")
   e.create('lynel_sword', 'sword').displayName("Lynel Sword").attackDamageBaseline(24.0).maxDamage(26).unstackable().rarity('common').tooltip("This Lynel-made sword was designed with smashing in mind rather than slicing. It's on the heavy side compared to what Hylians are used to, but it's very strong.")
   e.create('mlynel_sword', 'sword').displayName("Mighty Lynel Sword").attackDamageBaseline(36.0).maxDamage(32).unstackable().rarity('common').tooltip("This Lynel-made sword boasts more blades and more attack power. A skilled Lynel can draw this sword simply in passing and still cut a foe in two.")
   e.create('slynel_sword', 'sword').displayName("Savage Lynel Sword").attackDamageBaseline(58.0).maxDamage(41).unstackable().rarity('common').tooltip("A brutal sword carried by white-haired Lynels. The savage blades are strong enough to cut down any foe, no matter how strong.")
   e.create('vicious_sword', 'sword').displayName("Vicious Sickle").attackDamageBaseline(16.0).maxDamage(14).unstackable().rarity('common').tooltip("A grim weapon favored by the Yiga. The half-moon shape of the blade allows for the rapid delivery of fatal wounds and serves as a symbol of their terror. Its durability is low.")
   e.create('demon_sword', 'sword').displayName("Demon Carver").attackDamageBaseline(40.0).maxDamage(25).unstackable().rarity('common').tooltip("This lethal weapon is forged by the Yiga. Its unique shape facilitates the sound dispatching of any target and strikes fear into the hearts of all who see it.")
   e.create('boko_arm_sword', 'sword').displayName("Bokoblin Arm").attackDamageBaseline(5.0).maxDamage(5).unstackable().rarity('common').tooltip("A skeletal arm that keeps moving even after it's severed from its body. It's kind of gross to strap it to your back, but it'll do in a pinch. It's old and fragile, so it's quick to break.")
   e.create('liza_arm_sword', 'sword').displayName("Lizalfos Arm").attackDamageBaseline(12.0).maxDamage(8).unstackable().rarity('common').tooltip("The arm of a Stalizalfos that continues to struggle even in death. It can be used as a weapon, but it's very brittle. You can feel it wiggling when you strap it to your back...")
   e.create('farm_hoe', 'sword').displayName("Farming Hoe").attackDamageBaseline(16.0).maxDamage(6).unstackable().rarity('common').tooltip("A farming tool primarily used for tilling fields. Its fine craftsmanship is sturdy enough to withstand backbreaking fieldwork, but its battle applications are untested.")
   e.create('oar', 'sword').displayName("Boat Oar").attackDamageBaseline(14.0).maxDamage(8).unstackable().rarity('common').tooltip("Made for paddling boats, but it was made sturdy enough to fight strong currents. Maybe it's useful for self-defense in a pinch.")
   e.create('iron_sledgehammer', 'sword').displayName("Iron Sledgehammer").attackDamageBaseline(12.0).maxDamage(40).unstackable().rarity('common').tooltip("This large iron sledgehammer was originally used for mining, but it works reasonably well as a weapon too.")
   e.create('traveller_csword', 'sword').displayName("Traveller's Claymore").attackDamageBaseline(10.0).maxDamage(20).unstackable().rarity('common').tooltip("A basic two-handed sword often wielded by aspiring adventurers. Its immense weight can knock enemies' shields right out of their hands.")
   e.create('soldier_csword', 'sword').displayName("Soldier's Claymore").attackDamageBaseline(20.0).maxDamage(25).unstackable().rarity('common').tooltip("A two-handed sword designed for combat. It's heavy and hard to use but has decent build quality and durability.")
   e.create('knight_csword', 'sword').displayName("Knight's Claymore").attackDamageBaseline(38.0).maxDamage(30).unstackable().rarity('common').tooltip("Only the most confident of Hyrule Castle's knights carried this two-handed sword. Its cutting edge is finely honed.")
   e.create('royal_csword', 'sword').displayName("Royal Claymore").attackDamageBaseline(52.0).maxDamage(40).unstackable().rarity('common').tooltip("A two-handed sword issued to the Hyrulean royal family's immediate guard detail. Its powerful strikes are said to crush an opponent's body and resolve alike.")
   e.create('silver_lsword', 'sword').displayName("Silver Longsword").attackDamageBaseline(22.0).maxDamage(30).unstackable().rarity('common').tooltip("Although the Zora prefer spears to swords, they made this two-handed weapon using a special metal. It found popularity among Hylians for its unique design.")
   e.create('cobble_crusher', 'sword').displayName("Cobble Crusher").attackDamageBaseline(15.0).maxDamage(30).unstackable().rarity('common').tooltip("A Goron-made two-handed weapon. It's made from thick, hard metal and has no cutting edge, so it relies on its sheer weight to crush all opponents.")
   e.create('stone_smasher', 'sword').displayName("Stone Smasher").attackDamageBaseline(42.0).maxDamage(40).unstackable().rarity('common').tooltip("A two-handed weapon forged from a rare metal mined in Goron City. Its center of gravity is at its tip, so it uses centrifugal force and its sheer weight to smash opponents flat.")
   e.create('boulder_breaker', 'sword').displayName("Boulder Breaker").attackDamageBaseline(60.0).maxDamage(60).unstackable().rarity('common').tooltip("This two-handed weapon was once wielded by the Goron Champion Daruk. Daruk made swinging it around look easy, but a Hylian would need an immense amount of strength.")
   e.create('golden_csword', 'sword').displayName("Golden Claymore").attackDamageBaseline(28.0).maxDamage(30).unstackable().rarity('common').tooltip("Only the most talented Gerudo sword fighters carry this two-handed sword. It's actually much lighter than it appears and is surprisingly easy to wield.")
   e.create('eight_lsword', 'sword').displayName("Eightfold Longblade").attackDamageBaseline(32.0).maxDamage(25).unstackable().rarity('common').tooltip("A single-edged sword seldom seen in Hyrule. This weapon is passed down through the Sheikah tribe and has an astonishingly sharp edge ideal for slicing.")
   e.create('duality_sword', 'sword').displayName("Edge of Duality").attackDamageBaseline(50.0).maxDamage(35).unstackable().rarity('common').tooltip("A curious double-edged sword crafted using Sheikah technology. It was originally made for Hyrulean knights unfamiliar with single-edged blades.")
   e.create('ancient_bladesaw', 'sword').displayName("Ancient Bladesaw").attackDamageBaseline(55.0).maxDamage(50).unstackable().rarity('common').tooltip("This two-handed sword was forged using ancient Sheikah technology. Its unique rotating blades give it impressive cutting power that will slice enemies to shreds.")
   e.create('rusty_csword', 'sword').displayName("Rusty Claymore").attackDamageBaseline(12.0).maxDamage(10).unstackable().rarity('common').tooltip("A two-handed sword not properly cared for. Although it can be used as a weapon, its durability is very low. Don't expect it to last for more than a few strikes.")
   e.create('royalg_csword', 'sword').displayName("Royal Guard's Claymore").attackDamageBaseline(72.0).maxDamage(15).unstackable().rarity('common').tooltip("The Sheikah used the very essence of ancient technology to forge this greatsword. It was designed to oppose the Calamity, but its low durability made it impractical in battle.")
   e.create('gflameblade', 'sword').displayName("Great Flameblade").attackDamageBaseline(34.0).maxDamage(50).unstackable().rarity('common').tooltip("This magic-infused greatsword was forged in the fires of Death Mountain by Goron smiths in an ancient age. Attack when the blade glows red to expel flames.")
   e.create('gfrostblade', 'sword').displayName("Great Frostblade").attackDamageBaseline(30.0).maxDamage(40).unstackable().rarity('common').tooltip("This magic-infused greatsword was forged by smelting ore found in the Hebra Mountains' permafrost. Attack when the blade glows blue to expel freezing air.")
   e.create('gthunderblade', 'sword').displayName("Great Thunderblade").attackDamageBaseline(32.0).maxDamage(50).unstackable().rarity('common').tooltip("This magic-infused greatsword was forged by the Hyrulean royal family using lightning from the Hyrule Hills. Attack when the blade glows golden to expel lightning.")
   e.create('six_sword', 'sword').displayName("Sword of the Six Sages").attackDamageBaseline(48.0).maxDamage(50).unstackable().rarity('rare').tooltip("The Six Sages are said to have forged this longsword to seal a demon king in the world where the hero fought against the beasts of twilight. The blade shines with a holy luster.")
   e.create('biggoron_sword', 'sword').displayName("Biggoron's Sword").attackDamageBaseline(50.0).maxDamage(60).unstackable().rarity('rare').tooltip("A legendary greatsword forged by a Goron craftsman for a hero who traveled through time. The exceptionally sharp cutting edge is a testament to the craftsman's mastery.")
   e.create('fierce_deity_sword', 'sword').displayName("Fierce Deiety Sword").attackDamageBaseline(60.0).maxDamage(35).unstackable().rarity('rare').tooltip("A peculiar greatsword allegedly used by a hero from a world in which the moon threatened to fall. It slashes wildly in battle as if possessed by a fierce deity.")
   e.create('boko_bat', 'sword').displayName("Boko Bat").attackDamageBaseline(6.0).maxDamage(12).unstackable().rarity('common').tooltip("A clunky club made by a Bokoblin. If you swing it at an enemy's shield, it may be able to knock the shield out of your foe's hand.")
   e.create('sboko_bat', 'sword').displayName("Spiked Boko Bat").attackDamageBaseline(18.0).maxDamage(12).unstackable().rarity('common').tooltip("After much consideration by Bokoblins on how to improve the Boko bat, they simply attached sharp spikes to it. A skilled fighter can cause immense damage with this.")
   e.create('dbone_boko_bat', 'sword').displayName("Dragonbone Boko Bat").attackDamageBaseline(36.0).maxDamage(16).unstackable().rarity('common').tooltip("Used by only the toughest Bokoblin warriors, this Boko bat has been fortified by fossilized bone. It boasts a high durability and is strong enough to beat down powerful foes.")
   e.create('mob_club', 'sword').displayName("Moblin Club").attackDamageBaseline(9.0).maxDamage(12).unstackable().rarity('common').tooltip("A crudely fashioned club favored by Moblins. It's carved from a sturdy tree but is sloppily made, so it breaks easily.")
   e.create('smob_club', 'sword').displayName("Spiked Moblin Club").attackDamageBaseline(27.0).maxDamage(18).unstackable().rarity('common').tooltip("Animal bone has been affixed to this Moblin club to greatly improve its damage.")
   e.create('dbone_mob_club', 'sword').displayName("Dragonbone Moblin Club").attackDamageBaseline(45.0).maxDamage(24).unstackable().rarity('common').tooltip("The bone of an ancient beast has been affixed to this Moblin club, further increasing its damage. Moblins carrying these in battle are particularly dangerous.")
   e.create('lynel_crusher', 'sword').displayName("Lynel Crusher").attackDamageBaseline(36.0).maxDamage(20).unstackable().rarity('common').tooltip("This two-handed weapon is favored by the Lynels. It may be more accurate to call it a lump of metal than a weapon, but if wielded by a Lynel, it can pound you into a fine dust.")
   e.create('mlynel_crusher', 'sword').displayName("Mighty Lynel Crusher").attackDamageBaseline(54.0).maxDamage(25).unstackable().rarity('common').tooltip("This Lynel-made two-handed weapon has been reinforced to increase its durability and striking power. Its overwhelming heft will crush your foe, shield and all.")
   e.create('slynel_crusher', 'sword').displayName("Savage Lynel Crusher").attackDamageBaseline(78.0).maxDamage(35).unstackable().rarity('common').tooltip("This Lynel-made two-handed weapon is immensely heavy thanks to a rare metal from Death Mountain's peak. The power of its downward swing is in a class all its own.")
   e.create('windcleaver', 'sword').displayName("Windcleaver").attackDamageBaseline(40.0).maxDamage(25).unstackable().rarity('common').tooltip("This sword is favored by high-ranking members of the Yiga. When wielded by a proficient fighter, its unique shape cleaves the very wind and creates a vacuum.")
   e.create('mob_arm', 'sword').displayName("Moblin Arm").attackDamageBaseline(15.0).maxDamage(5).unstackable().rarity('common').tooltip("A Moblin bone that continues to move even after being detached from its body. The bone is thick enough to be used as a weapon but is extremely brittle and easily broken.")
   e.create('mop', 'sword').displayName("Wooden Mop").attackDamageBaseline(5.0).maxDamage(8).unstackable().rarity('common').tooltip("Just a mop to the untrained eye, it excels at tidying up the place. But it owes its sturdy construction to a true craftsman, so it actually has some combat merit.")
   e.create('pitchfork', 'sword').displayName("Farmer's Pitchfork").attackDamageBaseline(7.0).maxDamage(12).unstackable().rarity('common').tooltip("A farming tool used to collect hay efficiently. It's light enough to be used by anyone. The four prongs are very sharp.")
   e.create('harpoon', 'sword').displayName("Fishing Harpoon").attackDamageBaseline(8.0).maxDamage(12).unstackable().rarity('common').tooltip("A fisherman's tool that excels at catching large fish. Its particularly sharp spearhead makes it valuable as a weapon as well.")
   e.create('throwing_spear', 'sword').displayName("Throwing Spear").attackDamageBaseline(6.0).maxDamage(20).unstackable().rarity('common').tooltip("A specialized spear weighted to excel as a throwing weapon. It's perfectly balanced to be thrown farther than your average spear, able to pierce targets from a great distance.")
   e.create('traveller_spear', 'sword').displayName("Traveller's Spear").attackDamageBaseline(3.0).maxDamage(30).unstackable().rarity('common').tooltip("A spear used mainly by travelers to fend off wolves and other beasts. It's easy to hold and simple to use.")
   e.create('soldier_spear', 'sword').displayName("Traveller's Spear").attackDamageBaseline(7.0).maxDamage(35).unstackable().rarity('common').tooltip("A long spear once used by the guards of Hyrule Castle. Easy to use but difficult to master. The iron tip is very sturdy and the shaft will not burn when exposed to flame.")
   e.create('knight_halberd', 'sword').displayName("Knight's Halberd").attackDamageBaseline(13.0).maxDamage(40).unstackable().rarity('common').tooltip("A spear used by knights adept in mounted combat. The spearhead is modeled after an axe.")
   e.create('royal_halberd', 'sword').displayName("Royal Halberd").attackDamageBaseline(26.0).maxDamage(50).unstackable().rarity('common').tooltip("This spear was issued to the knights who guarded Hyrule Castle's throne room. Its ornate design was applied by a craftsman in service to the royal family.")
   e.create('forest_spear', 'sword').displayName("Forest Dweller's Spear").attackDamageBaseline(11.0).maxDamage(35).unstackable().rarity('common').tooltip("The Koroks made this spear for Hylians. The shaft is made from a light, sturdy wood, offering ease of use. The spearhead is made from a much harder wood, offering strength.")
   e.create('zora_spear', 'sword').displayName("Zora Spear").attackDamageBaseline(9.0).maxDamage(40).unstackable().rarity('common').tooltip("This spear is a Zora's weapon of choice. It's lighter than it looks due to being made from a special metal and is used by the Zora for both fishing and protecting their domain.")
   e.create('silver_spear', 'sword').displayName("Silverscale Spear").attackDamageBaseline(12.0).maxDamage(40).unstackable().rarity('common').tooltip("The most skilled Zora fighters wield this spear. Its beautiful fish-tail design belies its impressive strength; the spearhead can pierce even the toughest scales.")
   e.create('ceremonial_trident', 'sword').displayName("Ceremonial Trident").attackDamageBaseline(14.0).maxDamage(40).unstackable().rarity('common').tooltip("A spear modeled after the Lightscale Trident wielded by the Zora Champion Mipha. They may be identical in appearance, but this spear's strength and durability are inferior.")
   e.create('lightscale_trident', 'sword').displayName("Lightscale Trident").attackDamageBaseline(22.0).maxDamage(70).unstackable().rarity('common').tooltip("A spear of peerless grace cherished by the Zora Champion Mipha. Although Mipha specialized in healing abilities, her spearmanship was in a class all its own.")
   e.create('drill', 'sword').displayName("Drillshaft").attackDamageBaseline(14.0).maxDamage(50).unstackable().rarity('common').tooltip("Goron artisans used recycled metal to forge this weapon. The tip is made from an old excavation bore, which affords it unmatched piercing capabilities.")
   e.create('feathered_spear', 'sword').displayName("Feathered Spear").attackDamageBaseline(10.0).maxDamage(35).unstackable().rarity('common').tooltip("Its lightweight design is a hallmark of Rito craftsmanship. It's made from light and sturdy materials, which afford Rito warriors ease of use during aerial combat.")
   e.create('gerudo_spear', 'sword').displayName("Gerudo Spear").attackDamageBaseline(16.0).maxDamage(35).unstackable().rarity('common').tooltip("This spear's center of gravity is in its tip, making it a bit unwieldy for the average fighter. But in the hands of a skilled Gerudo warrior, it's a weapon of reliable strength.")
   e.create('serpentine_spear', 'sword').displayName("Serpentine Spear").attackDamageBaseline(12.0).maxDamage(35).unstackable().rarity('common').tooltip("The spearhead of this weapon is uniquely Sheikah in design. Spear masters of the Sheikah tribe can use the crescent shape to snag their opponents and deliver brutal cuts")
   e.create('ancient_spear', 'sword').displayName("Ancient Spear").attackDamageBaseline(30.0).maxDamage(50).unstackable().rarity('common').tooltip("This spear is the result of countless hours of research into the ancient technology used by Guardians. The glowing spearhead has high piercing potential.")
   e.create('rusty_halbard', 'sword').displayName("Rusty Halbard").attackDamageBaseline(5.0).maxDamage(15).unstackable().rarity('common').tooltip("A rusty polearm likely used by knights from an age past. The spearhead is in bad shape due to prolonged exposure to the elements, so its durability is low.")
   e.create('royalg_spear', 'sword').displayName("Roayl Guard's Spear").attackDamageBaseline(32.0).maxDamage(15).unstackable().rarity('common').tooltip("This Sheikah-made spear was created using ancient technology to combat the Calamity. Its attack power is very high, but a critical design flaw left it with poor durability.")
   e.create('flamespear', 'sword').displayName("Flamespear").attackDamageBaseline(24.0).maxDamage(50).unstackable().rarity('uncommon').tooltip("A magical spear forged in the magma of Death Mountain. Attack when the blade glows to expel powerful flames.")
   e.create('frostspear', 'sword').displayName("Frostspear").attackDamageBaseline(20.0).maxDamage(40).unstackable().rarity('uncommon').tooltip("A magical spear forged from ancient ice taken from the Hebra Mountains. Attack when the blade glows blue to chill the air and freeze your foe.")
   e.create('thunderspear', 'sword').displayName("Thunderspear").attackDamageBaseline(22.0).maxDamage(50).unstackable().rarity('uncommon').tooltip("A magical spear that contains thunder from Thundra Plateau in its tip. Attack when the blade glows with a golden light to unleash an electrical attack.")
   e.create('boko_spear', 'sword').displayName("Boko Spear").attackDamageBaseline(2.0).maxDamage(12).unstackable().rarity('common').tooltip("A spear recklessly carved from a tree branch. Useful for skewering fish and meat, which can then be cooked over a flame. If it's close to breaking, consider throwing it.")
   e.create('sboko_spear', 'sword').displayName("Spiked Boko Spear").attackDamageBaseline(6.0).maxDamage(15).unstackable().rarity('common').tooltip("A Boko spear enhanced with sharpened animal bones. It's light, easy to use, and deals a decent amount of damage.")
   e.create('dbone_boko_spear', 'sword').displayName("Dragonbone Boko Spear").attackDamageBaseline(12.0).maxDamage(20).unstackable().rarity('common').tooltip("This Boko spear has been strengthened with fossilized bones. The bones are positioned outward so the fangs bite at the opponent. Beware Bokoblins carrying this weapon.")
   e.create('mob_spear', 'sword').displayName("Moblin Spear").attackDamageBaseline(4.0).maxDamage(15).unstackable().rarity('common').tooltip("This wooden spear is most often used by Moblins. It's made from a hastily whittled tree, so its stabbing power and durability are both pretty low.")
   e.create('smob_spear', 'sword').displayName("Spiked Moblin Spear").attackDamageBaseline(9.0).maxDamage(20).unstackable().rarity('common').tooltip("This Moblin-made spear uses a horned animal bone as the spearhead. Like many Moblin weapons it's sloppily made, but this one packs some respectable piercing power.")
   e.create('dbone_mob_spear', 'sword').displayName("Dragonbone Moblin Spear").attackDamageBaseline(15.0).maxDamage(25).unstackable().rarity('common').tooltip("This spear is a fan favorite among Moblins. The spearhead is made from fossilized bones adorned with spikes, which greatly increases its stabbing power.")
   e.create('liza_spear', 'sword').displayName("Lizal Spear").attackDamageBaseline(7.0).maxDamage(18).unstackable().rarity('common').tooltip("The brutal, ripping edge of this weapon’s spearhead is a distinctly Lizalfos design. Its low durability doesn’t lend itself to extended use.")
   e.create('eliza_spear', 'sword').displayName("Enhanced Lizal Spear").attackDamageBaseline(12.0).maxDamage(22).unstackable().rarity('common').tooltip("Judging by the harpoon-like spearhead of this Lizalfos-made spear, the Lizalfos use it for fishing as well as combat. Try not to get caught on the wrong end of its barbs.")
   e.create('fliza_spear', 'sword').displayName("Forked Lizal Spear").attackDamageBaseline(18.0).maxDamage(28).unstackable().rarity('common').tooltip("Skilled Lizalfos warriors tend to favor this spear. What it lacks in piercing power, it makes up for with the brutal wounds its dual ripping blades will inflict.")
   e.create('guardian_spear', 'sword').displayName("Guardian Spear").attackDamageBaseline(10.0).maxDamage(20).unstackable().rarity('common').tooltip("Wielded by Guardian Scouts, this spear has a high piercing power and is a testament to the Sheikah's high level of technology. the spearhead appears only when brandished.")
   e.create('plus_guardian_spear', 'sword').displayName("Guardian Spear+").attackDamageBaseline(15.0).maxDamage(25).unstackable().rarity('common').tooltip("The tip of this Guardian spear has been enlarged and strengthened. It's a bit shorter than your average spear, perhaps to facilitate use in tight spaces.")
   e.create('dplus_guardian_spear', 'sword').displayName("Guardian Spear++").attackDamageBaseline(20.0).maxDamage(35).unstackable().rarity('common').tooltip("This Guardian spear's output has been boosted to the maximum. The spearhead is designed for optimal stabbing, capable of easily piercing most armor.")
   e.create('lynel_spear', 'sword').displayName("Lynel Spear").attackDamageBaseline(14.0).maxDamage(25).unstackable().rarity('common').tooltip("The crescent-shaped spearhead of this Lynel-made weapon gives it poor balance, making it difficult to wield. Lynels, however, can swing it effectively with a single hand.")
   e.create('mlynel_spear', 'sword').displayName("Mighty Lynel Spear").attackDamageBaseline(20.0).maxDamage(35).unstackable().rarity('common').tooltip("The weight and cutting edge of this Lynel-made spear have both been enhanced. It's immensely heavy for a Hylian, but a Lynel can cleave through rock with a single swing.")
   e.create('slynel_spear', 'sword').displayName("Savage Lynel Spear").attackDamageBaseline(30.0).maxDamage(45).unstackable().rarity('common').tooltip("White-haired Lynels favor this brutal spear. Its axe-like spearhead and exceptional weight give it absolute destructive power.")



   //e.create('', 'sword').displayName("").attackDamageBaseline(.0).maxDamage().unstackable().rarity('common').tooltip("")

   //+


//axes
   e.create('woodcutters_axe', 'axe').displayName("Woodcutter's Axe").attackDamageBaseline(3.0).maxDamage(47).unstackable().rarity('common').tooltip("A woodcutter's tool of choice for felling trees. Its formidable weight and uneven balancing make it a slow, inefficient weapon.")
   e.create('double_axe', 'axe').displayName("Double Axe").attackDamageBaseline(18.0).maxDamage(52).unstackable().rarity('common').tooltip("This double-sided axe was designed with fighting in mind. It's a bit unwieldy, so it requires a well-practiced technique to use efficiently.")
   e.create('ancient_battle_axe', 'sword').displayName("Ancient Battle Axe").attackDamageBaseline(30.0).maxDamage(15).unstackable().rarity('common').tooltip("A weapon used by Guardian Scouts. Its unique blade was forged using ancient technology. Although powerful, its unusual shape causes it to break easily.")
   e.create('plus_ancient_battle_axe', 'sword').displayName("Ancient Battle Axe+").attackDamageBaseline(45.0).maxDamage(20).unstackable().rarity('common').tooltip("This ancient battle axe's damage output has been increased to maximum. It's sharp enough to cut through almost anything, so it may have been used to forge new routes.")
   e.create('dplus_ancient_battle_axe', 'sword').displayName("Ancient Battle Axe++").attackDamageBaseline(60.0).maxDamage(25).unstackable().rarity('common').tooltip("This ancient battle axe's damage output is scaled up to peak performance. Ancient technology makes it possible to enhance cutting power beyond metal weapons' limits.")
  
   //special community weapons
   e.create('one_hit_sword', 'sword').displayName("One-Hit-Obliterator").attackDamageBaseline(99999.0).maxDamage(99999).unstackable().rarity('common').tooltip("A weapon that defeats foes with one hit and causes the user to die from one hit. It loses its sheen and power after two consecutive uses, but will eventually regain both.")
  })

